name: Build Docker snapshot image and push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: registry.cn-shanghai.aliyuncs.com
  IMAGE_NAME: webui-model-helper

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Github Container Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - uses: docker/setup-buildx-action@v2

      - name: Docker Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          file: ./Dockerfile
          #tags: ${{ steps.meta.outputs.tags }}
          tags: |
            registry.cn-shanghai.aliyuncs.com/aweminds/webui-model-helper:snapshot
            registry.cn-shanghai.aliyuncs.com/aweminds/webui-model-helper:snapshot-${{ steps.date.outputs.today }}
          labels: ${{ steps.meta.outputs.labels }}
